import test from './cardv0_2.gltf'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import {useFrame } from '@react-three/fiber'

import React, { Suspense, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = (props) => {
  const group = useRef();
  const [active, setActive] = useState(false)
  const [hovered, setHover] = useState(false)
  const [bloc, setBloc] = useState(false)
  const { nodes, materials } = useGLTF(test);
  useFrame((state, delta) => {
    // mesh.current.rotation.x += 0.01,
        if(bloc){
            group.current.rotation.y += 0
        }
        else if(active) {
            group.current.rotation.y += .01
        }else{
            group.current.rotation.y -= .01
        }
    })
    
  return (
        <group ref={group} {...props} rotateX={90} dispose={null}>
            <group 
                rotation={[-Math.PI / 2, 0, Math.PI]}
                onClick={(event) =>{ 
                    setActive(!active)
                }}
                onPointerOver={(event) => {
                    setHover(true)
                    setBloc(true)
                }}
                onPointerOut={(event) => {
                    setHover(false)
                    setBloc(false)
                    
                }}>

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials["Material.005"]}
                />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_1.geometry}
                material={materials["Material.006"]}
                />
            </group>
        </group>
  );
}

useGLTF.preload(test);
